#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 the mpc-vst-dragonfly contributors
"""gen_formats.py <upstream-plugin-dir> <out formats.h> -- the original UI's value formats, per parameter.

Reads upstream's UI.cpp (vendored as UI.cpp.ref: reference only, never compiled) for every
createLabelledKnob(&params[paramX], "<printf format>", ...) and every level slider (setId(paramX): upstream prints
those with "%i%%", the value truncated to an int), maps paramX to its index through DistrhoPluginInfo.h's
enum Parameters, and writes DF_FORMATS[] for vst/dragonfly_vst.cpp's display strings. Params with no format
(option lists) get NULL and keep showing their option name.
"""
import re
import sys

src_dir, out = sys.argv[1], sys.argv[2]
info = open(src_dir + "/DistrhoPluginInfo.h").read()
enum = re.search(r"enum\s+Parameters\s*\{(.*?)\}", info, re.S).group(1)
names = [n.strip().split("=")[0].strip() for n in re.sub(r"//[^\n]*", "", enum).split(",") if n.strip()]
names = [n for n in names if n != "paramCount"]
ui = open(src_dir + "/UI.cpp.ref").read()
fmt = {}
for p, f in re.findall(r'createLabelledKnob\s*\(\s*&params\[(\w+)\]\s*,\s*"([^"]*)"', ui):
    fmt[p] = f
for p in re.findall(r"->setId\s*\(\s*(\w+)\s*\)", ui):
    fmt[p] = "%i%%"
missing = [n for n in names if n not in fmt]
lines = ["/* GENERATED by vst/gen_formats.py from upstream's UI.cpp: the original UI's value formats. */",
         "static const char *const DF_FORMATS[] = {"]
for n in names:
    lines.append('    %s,  /* %s */' % ('"%s"' % fmt[n] if n in fmt else "NULL", n))
lines.append("};")
open(out, "w").write("\n".join(lines) + "\n")
print("formats: %d of %d params (%s without: option lists)" % (len(names) - len(missing), len(names), ",".join(missing) or "none"))
